### PR TITLE
Add Vagrantfile for development

### PR DESCRIPTION
**Pull request by HexaCubist**
Vagrantfiles automate the creation of a development server. It will make a default superadmin user with email 'admin@example.com' and password 'admin' - from there you can log in at http://127.0.0.1:8000/.

While not for everyone, this could help hugely for people who might just want to try the tool or do work without comitting time and/or resources into provisioning a server or setting up a VM from scratch. You can read more about it here: https://www.vagrantup.com/

### CODE REVIEW

**Comment by abelardopardo** [comment]
Thanks for the request. I have a question. Django deployments come with the manage.py script which runs quite a comprehensive collection of commands directly on the relational model. One of those commands is "[createsuperuser](https://drive.google.com/file/d/1VCkgUYS1wbercjiuHfUmQ0DcLYW3SHEk/view?usp=sharing)" 

Do you think it is useful to have this functionality duplicated in two locations?

**Comment by abelardopardo** [comment]
The script you are providing packages the deployment steps included in the documentation. One possibility is to extend that script to include the invocation to manage.py createsuperuser. See if you can include those changes and we'll look at the merge.

**Comment by HexaCubist** [comment]
Hi @abelardopardo - thanks for the comments. Sorry this took so long - got caught up in other things but came back in my own time and got comfortable with Ruby to make the plugin required to create a superuser from the host. I have also updated the vagrantfile to work with the latest edition of OnTask (running on Python 3).

With the latest commit, you can use the command like so:

    Usage: vagrant createsuperuser -e [email=admin@example.com] -p [password=admin]
    
        -e, --email EMAIL                Specify the email (otherwise admin@example.com)
        -p, --pass PASSWORD              Specify the password (otherwise admin)
        -h, --help                       Print this help

Let me know what your thoughts are & if there is anything else that needs to be done before it is ready to be merged.

(also, very cool to see some of the design ideas we played with in the material design project coming through!)

**Comment by HexaCubist** [comment]
Updated this patch to the latest version of OnTask and retested - worked fine without any changes.

**Comment by HexaCubist** [comment]
Haven't had time to look at this yet - from a quick update it doesn't seem to work. I'll have a play with it when I'm more free in a week or so. Good to see docker support being worked on!

**Pull request closed without merging**
